# docker-compose.yml
version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: mealapp_db
    restart: always
    environment:
      POSTGRES_USER: mealuser
      POSTGRES_PASSWORD: mealpassword
      POSTGRES_DB: mealapp_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: